name: saropa_task
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  syncfusion_flutter_gauges: ^26.1.41

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

